# Generated by Django 5.0.6 on 2024-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('startsite_id', models.IntegerField(default=0)),
                ('endsite_id', models.IntegerField(default=0)),
                ('vehicle_id', models.IntegerField(default=0)),
                ('goods_id', models.IntegerField(default=0)),
                ('created_time', models.FloatField(default=1721492740.96752)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('time', '时间'), ('vehicle', '车'), ('ton', '吨'), ('cube', '方'), ('block', '块')], default='time', max_length=255)),
                ('contractorPrice', models.FloatField(default=0.0)),
                ('startSubsidy', models.FloatField(default=0.0)),
                ('endSubsidy', models.FloatField(default=0.0)),
                ('endPayment', models.FloatField(default=0.0)),
                ('driverPrice', models.FloatField(default=0.0)),
                ('if_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
