# Generated by Django 5.0.6 on 2024-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_time', models.FloatField(default=1721492740.965519)),
                ('if_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=255)),
                ('created_time', models.FloatField(default=1721492740.96652)),
                ('if_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('manager', models.CharField(max_length=255, null=True)),
                ('manager_phone', models.BigIntegerField(default=0, null=True)),
                ('type', models.CharField(choices=[('start', 'Start'), ('end', 'End')], default='start', max_length=20)),
                ('created_time', models.FloatField(default=1721492740.965519)),
                ('if_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site2owner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('phone', models.BigIntegerField(default=0)),
                ('created_time', models.FloatField(default=1721492740.96652)),
                ('if_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver', models.CharField(max_length=255)),
                ('license', models.CharField(max_length=255)),
                ('phone', models.BigIntegerField(default=0, null=True)),
                ('created_time', models.FloatField(default=1721492740.96652)),
                ('if_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
