# Generated by Django 5.0.6 on 2024-07-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_time',
            field=models.FloatField(default=1720598840.716364),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.FloatField(default=1720598840.716364),
        ),
    ]
