# Generated by Django 5.0.6 on 2024-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_login_time_alter_user_register_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_time',
            field=models.FloatField(default=1721492740.962114),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.FloatField(default=1721492740.962114),
        ),
    ]
